[project]
name = "adk-workshop-jc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-adk>=2.6.2",
    "google-cloud-aiplatform[adk,agent-engines]>=1.112",
    "ipykernel>=7.3.0",
    "litellm>=1.95.0",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "rich>=15.0.0",
]
